# Generated by Django 3.2.7 on 2021-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_alter_books_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='1997-12-12'),
            preserve_default=False,
        ),
    ]
