# Generated by Django 3.2.7 on 2021-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_alter_books_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateField(blank=True),
        ),
    ]
