# Generated by Django 3.2.7 on 2021-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_alter_books_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
