# Generated by Django 3.2.7 on 2021-10-02 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one', '0006_fruits'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='highlighted',
            field=models.TextField(default='8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruits',
            name='owner',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='auth.user'),
            preserve_default=False,
        ),
    ]
